"""Output-envelope schemas for the 11 in-scope tools (v5.2).

Each tool that emits structured content alongside its rendered text response
declares a permissive pydantic envelope. The JSON Schema generated by
``BaseModel.model_json_schema()`` is attached to ``Tool.outputSchema`` so MCP
clients can advertise / validate the shape.

**Permissive by design.** All envelopes use ``extra='allow'`` so service-layer
additions (new optional fields, error metadata, etc.) don't break the contract.
Validation in the SDK then acts as a *guard* against gross shape regressions
rather than a strict typed contract — that strict typing is scheduled for v6.0
once every service-layer return path is fully audited.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class _OutputBase(BaseModel):
    """Permissive base for output envelopes."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)


# ─── azure_price_search ─────────────────────────────────────────────────


class PriceSearchOutput(_OutputBase):
    """Envelope for ``azure_price_search``."""

    items: list[dict[str, Any]] = Field(default_factory=list)
    count: int = 0
    currency: str = "USD"


# ─── azure_price_compare ────────────────────────────────────────────────


class PriceCompareOutput(_OutputBase):
    """Envelope for ``azure_price_compare``."""

    service_name: str
    currency: str = "USD"
    comparisons: list[dict[str, Any]] | dict[str, Any] = Field(default_factory=list)


# ─── azure_cost_estimate ────────────────────────────────────────────────


class CostEstimateOutput(_OutputBase):
    """Envelope for ``azure_cost_estimate``."""

    # ``error`` set on the failure path — kept optional so the success
    # envelope doesn't need it.
    error: str | None = None
    service_name: str | None = None
    sku_name: str | None = None
    region: str | None = None
    currency: str | None = None


# ─── azure_region_recommend ─────────────────────────────────────────────


class RegionRecommendOutput(_OutputBase):
    """Envelope for ``azure_region_recommend``."""

    error: str | None = None
    service_name: str | None = None
    sku_name: str | None = None
    currency: str | None = None
    recommendations: list[dict[str, Any]] = Field(default_factory=list)


# ─── azure_ri_pricing ───────────────────────────────────────────────────


class RIPricingOutput(_OutputBase):
    """Envelope for ``azure_ri_pricing``."""

    currency: str = "USD"
    count: int = 0
    ri_items: list[dict[str, Any]] = Field(default_factory=list)
    comparison: list[dict[str, Any]] = Field(default_factory=list)


# ─── azure_bulk_estimate ────────────────────────────────────────────────


class BulkEstimateOutput(_OutputBase):
    """Envelope for ``azure_bulk_estimate``."""

    resource_count: int = 0
    unique_specs: int = 0
    successful: int = 0
    failed: int = 0
    currency: str = "USD"
    line_items: list[dict[str, Any]] = Field(default_factory=list)
    totals: dict[str, Any] = Field(default_factory=dict)
    errors: list[dict[str, Any]] = Field(default_factory=list)


# ─── azure_sku_discovery ────────────────────────────────────────────────


class SKUDiscoveryOutput(_OutputBase):
    """Envelope for ``azure_sku_discovery`` (canonical fuzzy-match)."""

    service_found: str | None = None
    original_search: str
    match_type: str | None = None
    total_skus: int = 0
    skus: dict[str, Any] = Field(default_factory=dict)
    suggestions: list[dict[str, Any]] = Field(default_factory=list)


# ─── azure_discover_skus (deprecated alias) ─────────────────────────────


class DiscoverSKUsOutput(_OutputBase):
    """Envelope for the ``azure_discover_skus`` deprecated alias.

    Per the v5.0 alias path, this returns a reshaped dict (list-of-dicts SKUs).
    """

    service_name: str
    total_skus: int = 0
    skus: list[dict[str, Any]] = Field(default_factory=list)


# ─── find_orphaned_resources ────────────────────────────────────────────


class OrphanedResourcesOutput(_OutputBase):
    """Envelope for ``find_orphaned_resources``."""

    error: str | None = None
    subscriptions: list[dict[str, Any]] = Field(default_factory=list)
    total_orphaned: int = 0
    total_estimated_cost: float = 0.0
    lookback_days: int = 60
    currency: str = "USD"


# ─── databricks_dbu_pricing ─────────────────────────────────────────────


class DatabricksDBUPricingOutput(_OutputBase):
    """Envelope for ``databricks_dbu_pricing``."""

    region: str | None = None
    currency: str = "USD"
    total_items: int = 0
    workloads: dict[str, list[dict[str, Any]]] = Field(default_factory=dict)


# ─── github_pricing ─────────────────────────────────────────────────────


class GitHubPricingOutput(_OutputBase):
    """Envelope for ``github_pricing``."""

    currency: str = "USD"
    data_version: str | None = None
    sections: dict[str, Any] = Field(default_factory=dict)


# ─── Registry ───────────────────────────────────────────────────────────


# Tool name → output-envelope class. Used by ``tools.py`` to attach
# ``outputSchema`` and by ``handlers.py`` to validate emitted payloads
# (defensively — the SDK also validates).
OUTPUT_SCHEMAS: dict[str, type[_OutputBase]] = {
    "azure_price_search": PriceSearchOutput,
    "azure_price_compare": PriceCompareOutput,
    "azure_cost_estimate": CostEstimateOutput,
    "azure_region_recommend": RegionRecommendOutput,
    "azure_ri_pricing": RIPricingOutput,
    "azure_bulk_estimate": BulkEstimateOutput,
    "azure_sku_discovery": SKUDiscoveryOutput,
    "azure_discover_skus": DiscoverSKUsOutput,
    "find_orphaned_resources": OrphanedResourcesOutput,
    "databricks_dbu_pricing": DatabricksDBUPricingOutput,
    "github_pricing": GitHubPricingOutput,
}


def get_output_schema(tool_name: str) -> dict[str, Any] | None:
    """Return the JSON Schema dict for ``tool_name`` or ``None`` if unschematized."""
    model_cls = OUTPUT_SCHEMAS.get(tool_name)
    if model_cls is None:
        return None
    return model_cls.model_json_schema()
